Revert "fix: Add evolve --abort to bb_hg_upload"
This reverts commit 18836054e497d1b918ab3ad8edce627f1dec5af6.

diff --git a/home/bin/executable_bb_hg_upload b/home/bin/executable_bb_hg_upload
--- a/home/bin/executable_bb_hg_upload
+++ b/home/bin/executable_bb_hg_upload
@@ -1,11 +1,9 @@
 #!/bin/bash
 
-set -e
+# The `hg evolve` command may fail if there are no changes to evolve.
+hg evolve --any
 
-if ! hg evolve; then
-  hg evolve --abort
-  echo "Evolve failed, aborted."
-  exit 1
-fi
+# But the following commands MUST always succeed.
+set -e
 hg fix
 hg upload tree
