fix: Add evolve --abort to bb_hg_upload

diff --git a/home/bin/executable_bb_hg_upload b/home/bin/executable_bb_hg_upload
--- a/home/bin/executable_bb_hg_upload
+++ b/home/bin/executable_bb_hg_upload
@@ -1,9 +1,11 @@
 #!/bin/bash
 
-# The `hg evolve` command may fail if there are no changes to evolve.
-hg evolve --any
-
-# But the following commands MUST always succeed.
 set -e
+
+if ! hg evolve; then
+  hg evolve --abort
+  echo "Evolve failed, aborted."
+  exit 1
+fi
 hg fix
 hg upload tree
